
name: chair_smp_seq_smth_l1_relative_targets_2

dataloader:
  num_input_frames: 3
  num_workers: 8
  sample_all_verts: True
model:
  loss_type: "smooth_l1_loss"
  vibe_model:
    relative_targets: True
