DATA:
  data_name: scannet_3d_vote
  data_root: /home/songyou/disk2/matterport_3d
  classes: 20
  aug: False
  voxelSize: 0.02
  feat_2d: mseg_voting # lseg_vote_labels | mseg_voting
  prompt_eng: True
  mark_no_feature_to_unknown: False

  use_one_shot_feat: False
  pred_type: 'fusion' # 'distill' | 'fusion'
  vis_pred: False
  vis_gt: False


  
TRAIN:
  viewNum: 1
  weight_2d: 0.1
  arch: disnet
  layers_2d: 34
  arch_3d: MinkUNet18A
  val_benchmark: False

  sync_bn_2d: False
  ignore_label: 255
  train_gpu: [0]
  workers: 0  # data loader workers
  batch_size: 1  # batch size for training
  batch_size_val: 1  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0001
  loop: 5
  epochs: 1000
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.000
  manual_seed: 1463
  print_freq: 10
  save_freq: 1
  save_path:
  weight:  # path to initial weight (default: none)
  resume:
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1
#  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
#  train_h: 241
#  train_w: 321
#  viewNum: 3

Distributed:
  dist_url: tcp://127.0.0.1:6787
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0


TEST:
  split: test # split in [train, val and test]
  val_benchmark: True
  test_workers: 8
  test_gpu: [0]
  test_batch_size: 1
  model_path:
  save_folder: tmp_mseg
  test_repeats: 5