dataset: blender
batching: every_image # all_images
factor: 2
num_coarse_samples: 128
num_fine_samples: 0
use_viewdirs: true
white_bkgd: true
batch_size: 1024
randomized: true
lr_init: 5.0e-4
lr_final: 1.0e-4
lr_delay_steps: 0
lr_delay_mult: 0
lr_init_pose: 1.0e-3
lr_final_pose: 1.0e-5
lr_delay_steps_pose: 0
lr_delay_mult_pose: 0
max_steps: 200000
save_every: 50000
render_every: 2000
gc_every: 5000
opt_camera: true
use_c2f: true
print_every: 2000
camera_noise: 0.15
init_poses_from_gt: true
sigma_activation: softplus
