name: Res32_d25_imagenet200
print_freq: 40
workers: 32
log_dir: 'logs'
model_dir: 'ckps'

# dataset & model setting
dataset: 'imagenet200'
data_path:  '/home/exx/PycharmProjects/hpn/data/' #'./data/cifar/cifar-10-batches-py/'
num_classes: 200
backbone: 'ResNet'
fixed_classifier: True
space_dim: 50


# distributed training
deterministic: False
distributed: False
gpu: 1
world_size: -1
rank: -1
dist_url: 'tcp://224.66.41.62:23456'
dist_backend: 'nccl'
multiprocessing_distributed: False

# Train
lr: 0.01
batch_size: 128
weight_decay: 0.0001
num_epochs: 250
momentum: 0.9
drop1: 100
drop2: 200
