INTERACTIVE_MODELS_PATH: "./weights"
EXPS_PATH: "./model_mmdd_yyyy"

# Evaluation datasets
GRABCUT_PATH: "./data/GrabCut"
BERKELEY_PATH: "./data/Berkeley"
DAVIS_PATH: "./data/DAVIS345"
COCO_MVAL_PATH: "./data/COCO_MVal"
BraTS_PATH: "./data/BraTS20"
ssTEM_PATH: "./data/ssTEM"
OAIZIB_PATH: "./data/OAI-ZIB/iseg_slices"
OAI_PATH: "./data/OAI"
HARD_PATH: "./data/HARD"
HQSeg44K_PATH: "./data/HQSeg44K"

# Train datasets
SBD_PATH: "./data/SBD/dataset"
COCO_PATH: "./data/COCO_2017"
LVIS_v1_PATH: "./data/COCO_2017"
OPENIMAGES_PATH: "./data/OpenImages"
PASCALVOC_PATH: "./data/PascalVOC"
ADE20K_PATH: "./data/ADE20k/ADEChallengeData2016"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_WEIGHTS:
  HRNETV2_W18: "./weights/pretrained/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./weights/pretrained/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./weights/pretrained/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./weights/pretrained/hrnetv2_w48_imagenet_pretrained.pth"
  HRNETV2_W64: "./weights/pretrained/hrnetv2_w64_imagenet_pretrained.pth"
  MIT_B5: "./weights/pretrained/mit_b5_converted.pth"
  MIT_B4: "./weights/pretrained/mit_b4_converted.pth"
  MIT_B3: "./weights/pretrained/mit_b3_converted.pth"
  MIT_B2: "./weights/pretrained/mit_b2_converted.pth"
  MIT_B1: "./weights/pretrained/mit_b1_converted.pth"
  MIT_B0: "./weights/pretrained/mit_b0_converted.pth"
  HRF_BASE: "./weights/pretrained/hrt_base.pth"
  SWIN_BASE: "./weights/pretrained/swin_base_patch4_window12_384_22k.pth"
  SWIN_LARGE: "./weights/pretrained/swin_large_patch4_window12_384_22k.pth"

MAE_WEIGHTS:  
  VIT_BASE: "./weights/mae_pretrain_vit_base.pth"
  VIT_LARGE: "./weights/mae_pretrain_vit_large.pth"
  VIT_HUGE: "./weights/mae_pretrain_vit_huge.pth"
