_BASE_: univs_R50_vos_ytvos18.yaml
MODEL:
  WEIGHTS: 'pretrained/univs/univs_prompt_R50_bs24_f1_sa1b+coco_2x_200queries_a+casa.pth'
INPUT:
  SAMPLING_FRAME_NUM: 1
  SAMPLING_FRAME_RANGE: 10
  MIN_SIZE_TEST: 720
OUTPUT_DIR: output/inf/r50_a/stage1/ytvos18/