_BASE_: Base.yaml
MODEL:
  WEIGHTS: 'univs_swinb_stage2.pth'
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoderUniVS"
  UniVS:
    VISUAL_PROMPT_PIXELS_PER_IMAGE: 256
    VISUAL_PROMPT_ENCODER: True
    TEXT_PROMPT_ENCODER: True
    LANGUAGE_ENCODER_ENABLE: False
    PROMPT_AS_QUERIES: True
    VISUAL_PROMPT_TO_IMAGE_ENABLE: True
    TEXT_PROMPT_TO_IMAGE_ENABLE: True
    MASKDEC_ATTN_ORDER: 'casa'  # 'casa' or 'saca'
    MASKDEC_SELF_ATTN_MASK_TYPE: 'sep'  # 'all', 'sep', 'p2l-alpha', 'p2l-beta'
DATASETS:
  TEST: ("sot_ytbvos18_val", )
INPUT:
  SAMPLING_FRAME_NUM: 4
  MIN_SIZE_TEST: 720
OUTPUT_DIR: output/inf/r50_c1+univs/stage3/ytvos18/