name: rce
channels:
  - defaults
dependencies:
  - python=3.6
  - pip=21.1.3
  - numpy=1.19.2
  - absl-py=0.13.0
  - pyparsing=2.4.7
  - pip:
    - tf-agents==0.6.0
    - mujoco-py==2.0.2.10
    - mjrl @ git+git://github.com/aravindr93/mjrl@a38324680e76347bfc5040114017b443060b1e0d
    - gin-config==0.4.0
    - tensorflow==2.4.0rc0
    - tensorflow-probability==0.12.1
    - gym==0.12.1
    - mujoco-py==2.0.2.10
    - git+https://github.com/rlworkgroup/metaworld.git@dfdbc
