_BASE_: ../../univs/univs_swinl_stage3.yaml
MODEL:
  META_ARCHITECTURE: "UniVS_Prompt_LongVideo"
  BACKBONE:
    FREEZE_AT: 5
  SEM_SEG_HEAD:
    FROZEN_PIXEL_DECODER: False
    FROZEN_MASK_CONVS: False
    FROZEN_PREDICTOR: False
DATASETS:
  DATASET_RATIO: 
  # OD & IS
  - 0.15  # lvis
  - 0.15  # burst
  TRAIN: 
  # OD & IS
  - "lvis_v1_train_video"    # 100k (shared categories with burst)
  - "mots_burst_train"   
  TEST: ("sot_davis17_val", )
INPUT:
  SAMPLING_FRAME_NUM: 7
  SAMPLING_FRAME_RANGE: 40
  MIN_SIZE_TEST: 800
SOLVER:
  BASE_LR: 0.00005
  IMS_PER_BATCH: 2
  STEPS: (4000, )
  MAX_ITER: 5000  # 2x: (324k, 354k) for bs=8; (162k, 177k) for bs=16, (108k, 118k) for bs=24
TEST:
  DETECTIONS_PER_IMAGE: 35
OUTPUT_DIR: output/v2_ft_single_task/univs_swinl_stage3_burst/