name: Deploy PyPI
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pysr
    permissions:
      id-token: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: "Install building tools"
        run: pip install wheel
      - name: "Build package"
        run: python setup.py sdist bdist_wheel
      - name: "Publish distribution 📦 to Test PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          verbose: true
      - name: "Publish distribution 📦 to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
