model_path: 'pretrained/aslfeat/model.ckpt-380000'
hseq:
  root: "/local/hpatches-sequences-release"
  seq: ['v', 'i']
  start_idx: 0
  max_dim: 2000
  ignored_v: ['v_artisans', 'v_astronautis', 'v_talent']
  ignored_i: ['i_contruction', 'i_crownnight', 'i_dc', 'i_pencils', 'i_whitebuilding']
eval:
  err_thld: 3
net:
  max_dim: 2000
  config:
    kpt_n: 5000
    kpt_refinement: true
    deform_desc: 1
    score_thld: 0.5
    edge_thld: 10
    multi_scale: false
    multi_level: true
    nms_size: 3
    eof_mask: 5
    need_norm: true
    use_peakiness: true