DATA:
  data_name: scannet_3d_feat
  data_root: /home/songyou/disk2/matterport_nyu40_3d_new
  classes: 40
  aug: True
  voxelSize: 0.02
  feat_2d: osegclip_random_average_test
  input_color: False
  mark_no_feature_to_unknown: True
  prompt_eng: True
  pred_type: 'distill' # 'distill' | 'fusion' | 'ensemble'
  # use_img_feat: True
  comp_ensemble_ratio: False
  vis_pred: False
  vis_gt: False
  vis_mesh: False
  
TRAIN:
  viewNum: 1
  weight_2d: 0.1
  arch: disnet
  layers_2d: 34
  arch_3d: MinkUNet18A
  val_benchmark: False
  use_shm: False
  sync_bn_2d: False
  ignore_label: 255
  train_gpu: [0]
  workers: 8  # data loader workers
  batch_size: 8  # batch size for training
  batch_size_val: 1  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0001
  loss_type: cosine # l1 | cosine
  loop: 5
  epochs: 100
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  manual_seed: 3407
  print_freq: 10
  save_freq: 1
  weight:  # path to initial weight (default: none)
  resume:
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1

Distributed:
  dist_url: tcp://127.0.0.1:6787
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0


TEST:
  split: test  # split in [train, val and test]
  val_benchmark: True
  test_workers: 8
  test_gpu: [0]
  test_batch_size: 1
  model_path:
  save_folder:
  test_repeats: 5