_BASE_: univs_swinl_yt21_c1+univs_entity.yaml
DATASETS:
  TEST: ("ovis_dev0.01", )
INPUT:
  SAMPLING_FRAME_NUM: 3
  MIN_SIZE_TEST: 480
TEST:
  DETECTIONS_PER_IMAGE: 50
OUTPUT_DIR: output/inf/swinl_c1+univs/stage2/ovis/entity/