_BASE_: univs_R50_yt21_c1+univs.yaml
MODEL:
  WEIGHTS: 'pretrained/univs/univs_prompt_R50_bs16_f3_vis+vps_100k_200queries_c1+univs+casa.pth'
  META_ARCHITECTURE: "UniVS_Prompt"
  SEM_SEG_HEAD:
    NUM_CLASSES: 40
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoderUniVS"
    NUM_OBJECT_QUERIES: 200
  UniVS:
    TEST:
        VIDEO_UNIFIED_INFERENCE_ENABLE: True
  BoxVIS:
    TEST:
      NUM_FRAMES_WINDOW: 5
      APPLY_CLS_THRES: 0.25
DATASETS:
  TEST: ("ytvis_2021_val", )
INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 10
  MIN_SIZE_TEST: 640
TEST:
  DETECTIONS_PER_IMAGE: 35
OUTPUT_DIR: output/inf/r50_c1+univs/stage2/yt21/entity/