_BASE_: univs_R50_yt21_c1+univs_entity.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  UniVS:
    POSITION_EMBEDDING_SINE3D: 'FixedT'
    TEST:
      VIDEO_UNIFIED_INFERENCE_ENABLE: True
DATASETS:
  TEST: ("ytvis_2021_dev", )
INPUT:
  SAMPLING_FRAME_NUM: 5
  MIN_SIZE_TEST: 640
TEST:
  DETECTIONS_PER_IMAGE: 50
OUTPUT_DIR: output/inf/swinl_c1+univs/stage3/yt21/entity/