_BASE_: univs_R50_yt21_c1+univs.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: 'pretrained/univs/univs_prompt_swinl_bs4_f7_video_1x_200queries_c1+univs+casa_prompt+sa_frozenbb+pixelenc_cttloss.pth'
  BoxVIS:
    TEST:
      NUM_FRAMES_WINDOW: 3
      CLIP_STRIDE: 1
      LSJ_AUG_ENABLED: True
      TRACKER_TYPE: 'minvis'
      APPLY_CLS_THRES: 0.25
DATASETS:
  TEST: ("ytvis_2021_dev", )
INPUT:
  SAMPLING_FRAME_NUM: 5
  MIN_SIZE_TEST: 640
TEST:
  DETECTIONS_PER_IMAGE: 50
OUTPUT_DIR: output/inf/swinl_c1+univs/stage3/yt21/minvis/