data_name: 'fmbench'
data_split: ['TUM', 'KITTI', 'Tanks_and_Temples', 'CPC']
data_root: '/local/FM-Bench'
dump_root: '/local/FM-Bench/Features_aslfeat_ms'
truncate: [0, null]
model_path: 'pretrained/aslfeat/model.ckpt-380000'
overwrite: true
net:
  max_dim: 2048
  config:
    kpt_n: 20000
    kpt_refinement: true
    deform_desc: 1
    score_thld: 0.5
    edge_thld: 10
    multi_scale: true
    multi_level: true
    nms_size: 3
    eof_mask: 5
    need_norm: true
    use_peakiness: true