task:
  use_crf: false
  model:
    encoder:
      hidden_size: 256
      num_layers: 2
    input_embedding:
      shape_configs:
          token_ids:
            vocab_size: 25000
            embedding_size: 250
          token_type:
            vocab_size: 6
            embedding_size: 16
          is_upper:
            vocab_size: 2
            embedding_size: 8
          is_title:
            vocab_size: 2
            embedding_size: 8
