_BASE_: Base.yaml
MODEL:
  WEIGHTS: 'pretrained/univs/univs_prompt_r50_bs8_f3_referonly_2x_200queries_c1+univs+casa_prompt_sa_frozenbb_wlang2img+attn_weights.pth'
  META_ARCHITECTURE: "UniVS_Prompt"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoderUniVS"
    NUM_OBJECT_QUERIES: 200
  BoxVIS:
    TEST:
      NUM_FRAMES_WINDOW: 5
      CLIP_STRIDE: 1
      APPLY_CLS_THRES: 0.05
DATASETS:
  TEST: ("rvos-refdavis-val-0", "rvos-refdavis-val-1", "rvos-refdavis-val-2", "rvos-refdavis-val-3")
INPUT:
  SAMPLING_FRAME_NUM: 3
  MIN_SIZE_TEST: 720
OUTPUT_DIR: output/inf/r50_c1+univs/stage2/refer_davis/