_BASE_: univs_R50_refvos_davis_c1+univs.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: 'pretrained/univs/univs_prompt_swinb_bs8_f4_video_1x_200queries_c1+univs+casa_prompt+sa_frozenbb_ft_refer+burst.pth'
INPUT:
  SAMPLING_FRAME_NUM: 4
  MIN_SIZE_TEST: 720
OUTPUT_DIR: output/inf/swinb_c1+univs/stage3_refer+burst/refer_ytvos/