_BASE_: univs_R50_refvos_davis_c1+univs.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: 'pretrained/univs/univs_prompt_swinl_bs8_f3_video_2x_200queries_c1+univs+casa_prompt+sa_frozenbb.pth'
INPUT:
  SAMPLING_FRAME_NUM: 3
  MIN_SIZE_TEST: 720
OUTPUT_DIR: output/inf/swinl_c1+univs/stage2/refer_ytvos/