indicators:
  - class_name: Scalar
    is_print: false
    name: param.*
    options:
      comet: false
  - class_name: Scalar
    is_print: false
    name: grad.*
    options:
      comet: false
  - class_name: Scalar
    is_print: false
    name: module.*
    options:
      comet: false
  - class_name: Scalar
    is_print: false
    name: optim.*
    options:
      comet: false
#web_api: http://localhost:5005/api/v1/track?
