name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 6 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          days-before-stale: 90
          days-before-pr-stale: -1
          days-before-issue-close: 7
          days-before-pr-close: -1
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          exempt-issue-labels: 'bug, call for contribution, doc, enhancement, good first issue, help wanted, mxnet, question'
          ascending: true
          operations-per-run: 300
