# training on new model, rate, and data
model: qb4z_2lmb
model_pretrained: runs/cloc-rate-inc/qb4z_2lmb_4/last.pt
freeze: em
lmb:
  - 32 # lower bound
  - 4096 # upper bound
trainset: coco_train2017
batch_size: 16

# knowledge replay
replay_model: qb4z_2lmb
replay_lmb:
  - 32 # lower bound
  - 1024 # upper bound
replay_trainset: coco_train2017
replay_batch_size: 16

# evaluation
valset: kodak
val_batch_size: 1
