_BASE_: Base.yaml
MODEL:
  WEIGHTS: 'pretrained/univs/univs_prompt_R50_bs24_f1_sa1b+coco_2x_200queries_a+casa.pth'
  META_ARCHITECTURE: "BoxVIS_VideoMaskFormer"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoderUni"
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: False
      PANOPTIC_ON: True
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.05
      STABILITY_SCORE_THRESH: 0.0
DATASETS:
  TEST: ("coco_2017_val_panoptic_with_sem_seg", )
INPUT:
  SAMPLING_FRAME_NUM: 1
  SAMPLING_FRAME_RANGE: 10
  MIN_SIZE_TEST: 800
TEST:
  DETECTIONS_PER_IMAGE: 100
OUTPUT_DIR: output/inf/univs_r50_coco+sa1b_a+casa_coco/