name: persistentnature
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.3
  - cudnn
  - pip
  - ipython
  - numpy
  - click
  - pillow
  - tqdm
  - ninja
  - matplotlib
  - ipdb
  - jupyter
  - jupyterlab
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - torch==1.12.0+cu113
    - torchvision==0.13.0+cu113
    - imageio-ffmpeg==0.4.3
    - ftfy 
    - regex
    - git+https://github.com/openai/CLIP.git
    - git+https://github.com/davidbau/baukit
    - scikit-video
    - scipy
    - lpips
    - ipywidgets==7.7.1
    - ipyevents==2.0.1
    - einops
