# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
channels:
  - defaults
dependencies:
  - zip
  - bzip2
  - pip
  - python=3.9.6
  - wget
  - git
  - pip:
    - absl-py==1.2.0
    - bz2file==0.98
    - numpy==1.23.3
    - pandas==1.5.0