_BASE_: univs_R50_vps_c1+univs.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: 'pretrained/univs/univs_prompt_swinl_bs8_f3_video_2x_200queries_c1+univs+casa_prompt+sa_frozenbb.pth'
  BoxVIS:
    TEST:
      NUM_FRAMES_WINDOW: 5
      CLIP_STRIDE: 1
      LSJ_AUG_ENABLED: True
      TRACKER_TYPE: 'minvis'
      APPLY_CLS_THRES: 0.25
DATASETS:
  TEST: ("vipseg_panoptic_val", )
INPUT:
  SAMPLING_FRAME_NUM: 3
  MIN_SIZE_TEST: 720
TEST:
  DETECTIONS_PER_IMAGE: 100
OUTPUT_DIR: output/inf/swinl_c1+univs/stage2/vps/