DATA:
  data_name: scannet_3d_feat
  data_root: /home/songyou/disk3/nuscenes_3d_05sec
  classes: 16
  aug: False
  voxelSize: 0.05
  feat_2d: 05sec_osegclip # 05sec_osegclip | 05sec_lseg
  input_color: False
  mark_no_feature_to_unknown: True
  prompt_eng: True
  pred_type: 'ensemble' # 'distill' | 'fusion' | 'ensemble'
  map_nuscenes_details: True
  vis_pred: False
  vis_gt: False
  
TRAIN:
  viewNum: 1
  weight_2d: 0.1
  arch: disnet
  layers_2d: 34
  arch_3d: MinkUNet18A
  val_benchmark: False
  use_shm: False
  sync_bn_2d: False
  ignore_label: 255
  train_gpu: [0]
  workers: 8  # data loader workers
  batch_size: 8  # batch size for training
  batch_size_val: 1  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0001
  loss_type: cosine # l1 | cosine
  loop: 5
  epochs: 100
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  manual_seed: 3407
  print_freq: 10
  save_freq: 1
  weight:  # path to initial weight (default: none)
  resume:
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1

Distributed:
  dist_url: tcp://127.0.0.1:6787
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0


TEST:
  split: val  # split in [train, val and test]
  val_benchmark: True
  test_workers: 8
  test_gpu: [0]
  test_batch_size: 4
  model_path: /home/songyou/workspace/distill_net/Exp/nuscenes/osegclip_05sec_parallel/model/model_best.pth.tar
  save_folder: /home/songyou/workspace/distill_net/Exp/nuscenes/osegclip_05sec_parallel/model/
  # model_path: /home/songyou/workspace/distill_net/Exp/nuscenes/lseg_05sec_parallel/model/model_best.pth.tar
  # save_folder: /home/songyou/workspace/distill_net/Exp/nuscenes/lseg_05sec_parallel/result/val
  test_repeats: 5