seed: 2345
dataset: 'iwslt'
context_len: 0
graph_type: 'dense'
graph_attrs:
    window: 16

n_layers: 6
m_layers: 6
dim_embed: 512
dim_model: 512
dim_ff: 2048
num_heads: 8
dropouti: 0.1
dropouth: 0.1
dropouta: 0.1
dropoutc: 0.1
rel_pos: False

n_epochs: 40
lr: 1.e-3
grad_accum: 1
factor: 1
batch_size: 128
dev_batch_size: 128
test_batch_size: 64
log_interval: 100
doc_max_len: 100
sent_max_len: 64
warmup: 8000

save_name: 'iwslt-dense-sent'
