seed: 2345
dataset: 'multi'
graph_type: 'bpt'
graph_attrs:
    step: 4
    clip_dist: 2

n_layers: 6
m_layers: 6
dim_embed: 512
dim_model: 512
dim_ff: 2048
num_heads: 8
dropouti: 0.1
dropouth: 0.1
dropouta: 0.1
dropoutc: 0.1
rel_pos: True

n_epochs: 40
lr: 1.e-3
grad_accum: 1
factor: 1
batch_size: 128
dev_batch_size: 256
test_batch_size: 128
log_interval: 50
weight_decay: 5.e-5
doc_max_len: 64
sent_max_len: 64

save_name: 'multi-4'
