seed: 2345
dataset: 'snli'
graph_type: 'bpt'
graph_attrs:
    step: 4
    clip_dist: 2

n_layers: 3
m_layers: 3
dim_embed: 300
dim_model: 300
dim_ff: 600
num_heads: 6
dropouti: 0.5
dropouth: 0.1
dropouta: 0.3
dropoutc: 0.5
rel_pos: True

n_epochs: 200
lr: 2.5e-4
batch_size: 128
dev_batch_size: 128
opt_wrapper: 'exp_decay'
log_interval: 320
