name: gluon_vision_docs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
- python=3.7
- sphinx>=1.5.5
- scipy
- numpy
- matplotlib
- sphinx_rtd_theme
- pip=20.2
- pytorch=1.6.0
- torchvision=0.7.0
- pip:
  - https://github.com/mli/mx-theme/tarball/0.3.1
  - sphinx-gallery
  - https://repo.mxnet.io/dist/python/cu100mkl/mxnet_cu100mkl-1.6.0b20191010-py2.py3-none-manylinux1_x86_64.whl
  # - guzzle_sphinx_theme
  - recommonmark
  - Image
  - awscli
  - tqdm
  - requests
  - Pillow
  - opencv-python
  - portalocker
  - decord
  - cython
  - pycocotools
  - autocfg
  - yacs
