# arguments for dataset
dataset: cityscapes
nclass: 19
crop_size: 801
data_root: ./cityscapes

# arguments for training
epochs: 240
batch_size: 4 # per GPU x 4 GPUs
lr: 0.001
lr_multi: 1.0
criterion:
  name: OHEM
  kwargs:
    ignore_index: 255
    thresh: 0.7
    min_kept: 200000


# arguments for model
model:
  backbone:
    type: model.backbone.mit.mit_b5
    kwargs:
      embed_dims: [64, 128, 320, 512]
      pretrained: True
  decoder:
    type: model.semseg.semidec_base.SemiDecoder
    kwargs:
      num_heads: 2
      num_class: 19
      in_planes: [64, 128, 320, 512]
      image_size: 801
      embedding_dim: 768
