_BASE_: univs_r50_stage2.yaml
MODEL:
  META_ARCHITECTURE: "UniVS_Prompt_LongVideo"
  BACKBONE:
    FREEZE_AT: 5
  SEM_SEG_HEAD:
    FROZEN_PIXEL_DECODER: False
    FROZEN_MASK_CONVS: False
    FROZEN_PREDICTOR: False
  UniVS:
    NUM_POS_QUERIES: 20
DATASETS:
  DATASET_RATIO: 
  # OD & IS
  - 0.15  # lvis
  - 0.35  # ovis 42k
  - 0.25  # ytvis21 90k
  # VSS & VPS
  - 0.5   # entityseg
  - 0.25  # panoptic coco
  - 0.5   # vipseg 85k
  # Ref
  - 0.35  # refcoco
  - 0.5   # ref-ytvos
  # SOT & VOS
  - 0.25  # sa1b
  - 0.25  # ytvos18
  - 0.15  # mose
  - 0.15  # burst
  TRAIN: 
  # OD & IS
  - "lvis_v1_train_video"    # 100k (shared categories with burst)
  - "ovis_train"             # 35k  (551 videos)
  - "ytvis_2021_train"       # 90k  (2679 videos)
  # VPS
  - "entityseg_panoptic_train"  # 32k
  - "coco_panoptic_train"    # 117k
  - "vipseg_panoptic_train"  # 85k
  # Ref
  - "rvos_refcoco-mixed"     # 5.5k images
  - "rvos-refytb-train"      # 3.5k (3469 videos)
  # SOT & VOS
  - "sa_1b_train_250k_1"     # 250k
  - "sot_ytbvos18_train"     # 90k (3471 videos)
  - "mots_mose_train"        #
  - "mots_burst_train"   
  TEST: ("ytvis_2021_dev", )
INPUT:
  SAMPLING_FRAME_NUM: 7
  SAMPLING_FRAME_RANGE: 40
  MIN_SIZE_TEST: 800
  LSJ_AUG:
    SQUARE_ENABLED: False
SOLVER:
  BASE_LR: 0.000025
  IMS_PER_BATCH: 4
  STEPS: (342000, )
  MAX_ITER: 354000  # 2x: (324k, 354k) for bs=8; (162k, 177k) for bs=16, (108k, 118k) for bs=24
TEST:
  DETECTIONS_PER_IMAGE: 35
OUTPUT_DIR: output/v2/univs_r50_stage3/