# general settings
name: basicpbc_pbch_train
model_type: PBCModel
scale: 1
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: PaintBucket_Char
    type: PaintBucketLabelSegDataset
    aug_params:
      rotate: 20
      resize: 960
      crop: 640
      rotate_prob: 0.5
    root: dataset/train/PaintBucket_Char/
    merge_label_prob: 0.2
    shuffle_label: false
    color_redistribution_type: seg
    frame_distance_list: [0,1,2]

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
  val:
    name: PaintBucket_Char
    type: PaintBucketSegMat
    root: dataset/test/PaintBucket_Char/
    dstype: contour
    split: test
    is_png_seg: true
    color_redistribution_type: gt

# network structures
network_g:
  type: BasicPBC
  ch_in: 6
  descriptor_dim: 128
  keypoint_encoder: [32, 64, 128]
  GNN_layer_num: 9
  use_clip: true

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.999]
  
  scheduler:
    type: MultiStepLR
    milestones: [80000]
    gamma: 0.1
  
  ema_decay: 0.9
  total_iter: 800000
  warmup_iter: -1  # no warm up

  # losses
  l_ce:
    type: L_direct
    loss_weight: 1.0

# validation settings
val:
  val_freq: !!float 5e4
  save_img: true
  save_csv: true

  metrics:
    acc: # metric name
      type: none # can be arbitrary
    acc_thres:
      type: none
    pix_acc:
      type: none
    pix_acc_wobg:
      type: none
    bmiou:
      type: none
    pix_bmiou:
      type: none

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500