[Generator]
# the configuration of the generator, since the generator contains the 3 sub-networks, they are
# BGNet, SIDNet, TSFNet

name = "InputConcat"

    [Generator.BGNet]
        # the configuration of the Background Inpainting Network
        norm_type = "instance"             # use instance normalization
        cond_nc = 4                        # number channels of conditions, RGB (3) + MASK (1) = 4
        n_res_block = 6                    # number of residual blocks
        num_filters = [64, 128, 128, 256]  # number of filters

    [Generator.TSFNet]
        # the configuration of the Transfer Network
        num_source = 4
        each_source_cond_nc = 6
        norm_type = "instance"            # use instance normalization
        cond_nc = 27                       # number of conditions, 24 (num_source = 4 * 6) + 3 = 27
        n_res_block = 6                   # number of residual blocks.
        num_filters = [64, 128, 256]      # number of filters

[Discriminator]
name = "patch_global"
    # the configuration of the discriminator
    norm_type = "instance"            # use instance normalization;
    cond_nc = 6         # the number of conditions
    bg_cond_nc = 4      # the number of background conditions
    ndf = 64            # the number of the base filters for Discriminator;
    n_layers = 4        # the number of downsampling operations, convolution with stride = 2;
    max_nf_mult = 8     # the max multi fact, [ndf, ndf * 2, ndf * 4, ndf * 8, ndf * 8, ndf * 8, ...];
    use_sigmoid = false # here, we do not use Sigmoid, since we use LSGAN.
